---
# Install some useful utilities

- name: add backports repo
  apt_repository:
    repo="deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    state=present
    update_cache=yes

- name: install jq
  apt: name=jq=1.4-2.1~ubuntu14.04.1 state=present

- name: install httpie
  pip: name=httpie state=present

- name: install htop
  apt: name=htop state=present

- name: install mysql clients and utilities
  apt: name={{item}} state=present
  with_items:
    - mysql-client-core-5.6
    - mysql-utilities
    - python-mysqldb
